apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
spec:
  nodeName: worker-02
  containers:
  - name: iperf3
    image: alpine:3.19.1
    command: ["/bin/sh", "-c", "apk add --no-cache iperf3 && sleep 3600000"]
